apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-docker-testing
spec:
  vendor: eduk8s.io
  title: Docker Testing
  description: Play area for testing docker
  url: https://github.com/eduk8s-tests/lab-docker-testing
  content:
    files: github.com/eduk8s-tests/lab-docker-testing
  duration: 60m
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      docker:
        enabled: true
      registry:
        enabled: true
